crawler:
  driver:
    id: webdriver.chrome.driver
    path: C:\workspace\aa\storeCrawler\lib\chromedriver.exe
  ignoreProtectedModeSettings: true
  useAllowedIps: true
  useSecretMode: true
  useHeadlessMode: false
  files:
    database: C:\workspace\aa\storeCrawler\data\database.xlsx
    result: C:\workspace\aa\storeCrawler\data\result.xlsx
    log: C:\workspace\aa\storeCrawler\log\crawler.log
  logging:
    mode: NEW
  search:
    restaurant:
      - 애견 동반 식당
      - 반려 동반 식당
      - 강아지 함께 식당
      - 고양이 함께 식당
    cafe:
      - 애견 동반 카페
      - 반려 동반 카페
      - 강아지 함께 카페
      - 고양이 함께 카페
    hotel:
      - 애견 동반 호텔
      - 반려 동반 호텔
      - 강아지 함께 호텔
      - 고양이 함께 호텔
    pension:
      - 애견 동반 펜션
      - 반려 동반 펜션
      - 강아지 함께 펜션
      - 고양이 함께 펜션